### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [rexx0520/Telegram-Music-Bot#4]
`  File "C:\Python38\lib\site-packages\pymongo\database.py", line 107, in __init__
    raise TypeError("name must be an instance "
TypeError: name must be an instance of str`

**Comment by lekoOwO** [comment]
Wow, it's been a really old project.
Can you describe the details when u encounter this issue?
Like wut have u did (the commands)

BTW, it's recommended to deploy the instance my docker-compose (which setup your mongodb and system in a single command)

**Comment by Envel-Nikita-Gutsenkov** [comment]
this is a very interesting project.
I tried to run this using docker, but I get an error
docker
https://pastebin.com/hRmEQhp3
docker-compose up
ERROR: no such image: rexx0520/Telegram-Music-Bot: invalid reference format: repository name must be lowercase
maybe I just don't know how to work with it, but I would really like to launch a bot.

**Comment by lekoOwO** [comment]
U might want to try with the new `docker-compose` file

**Comment by Envel-Nikita-Gutsenkov** [comment]
Yes, it works fine now, you just had to lower the version: version: "3.3"

but I don't quite understand how to run it in real conditions, if you need to fill in the fields in docker-compose.bml
most of the questions to the field
MONGO_HOST : MongoDB 's URL.
e.g. : mongodb://user:pwd@host/python

suppose I installed a mongodb database locally, the username is "user" and the password is "password", what would the string look like in this case?

thank you for helping

**Comment by lekoOwO** [comment]
It's the [MongoDB Standard URI](https://docs.mongodb.com/manual/reference/connection-string/) I believe

**Comment by Envel-Nikita-Gutsenkov** [comment]
thanks, I'll try
